// Mocks generated by Mockito 5.x from annotations
// in selfcoach/test/clip_recorder_test.dart.
// Do not edit directly — re-run with:
//   dart run build_runner build

// ignore_for_file: no_leading_underscores_for_library_prefixes
// ignore_for_file: unused_import, prefer_const_constructors
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use, deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_declarations
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: unintended_html_in_doc_comment

import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:selfcoach/features/camera/camera_controller.dart' as _i2;
import 'package:selfcoach/shared/storage/local_storage_service.dart' as _i4;
import 'package:selfcoach/features/recording/clip_metadata.dart' as _i5;

// ignore_for_file: type=lint

/// A class which mocks [CameraControllerService].
class MockCameraControllerService extends _i1.Mock
    implements _i2.CameraControllerService {
  @override
  bool get isRecording =>
      (super.noSuchMethod(Invocation.getter(#isRecording),
          returnValue: false) as bool);

  @override
  bool get isStreamingImages =>
      (super.noSuchMethod(Invocation.getter(#isStreamingImages),
          returnValue: false) as bool);

  @override
  bool get isInitialized =>
      (super.noSuchMethod(Invocation.getter(#isInitialized),
          returnValue: false) as bool);

  @override
  _i3.Future<void> startVideoRecording(String? outputPath) =>
      (super.noSuchMethod(
          Invocation.method(#startVideoRecording, [outputPath]),
          returnValue: _i3.Future<void>.value(),
          returnValueForMissingStub:
              _i3.Future<void>.value()) as _i3.Future<void>);

  @override
  _i3.Future<String?> stopVideoRecording() =>
      (super.noSuchMethod(Invocation.method(#stopVideoRecording, []),
          returnValue: _i3.Future<String?>.value(),
          returnValueForMissingStub:
              _i3.Future<String?>.value()) as _i3.Future<String?>);

  @override
  _i3.Future<void> stopImageStream() =>
      (super.noSuchMethod(Invocation.method(#stopImageStream, []),
          returnValue: _i3.Future<void>.value(),
          returnValueForMissingStub:
              _i3.Future<void>.value()) as _i3.Future<void>);

  @override
  _i3.Future<void> dispose() =>
      (super.noSuchMethod(Invocation.method(#dispose, []),
          returnValue: _i3.Future<void>.value(),
          returnValueForMissingStub:
              _i3.Future<void>.value()) as _i3.Future<void>);

  @override
  _i3.Future<void> initialize({bool? enableAudio = true}) =>
      (super.noSuchMethod(
          Invocation.method(#initialize, [], {#enableAudio: enableAudio}),
          returnValue: _i3.Future<void>.value(),
          returnValueForMissingStub:
              _i3.Future<void>.value()) as _i3.Future<void>);
}

/// A class which mocks [LocalStorageService].
class MockLocalStorageService extends _i1.Mock
    implements _i4.LocalStorageService {
  @override
  _i3.Future<String> newClipPath() =>
      (super.noSuchMethod(Invocation.method(#newClipPath, []),
          returnValue: _i3.Future<String>.value(''),
          returnValueForMissingStub:
              _i3.Future<String>.value('')) as _i3.Future<String>);

  @override
  _i3.Future<String> newThumbnailPath() =>
      (super.noSuchMethod(Invocation.method(#newThumbnailPath, []),
          returnValue: _i3.Future<String>.value(''),
          returnValueForMissingStub:
              _i3.Future<String>.value('')) as _i3.Future<String>);

  @override
  _i3.Future<String> newTempPath(String? suffix) =>
      (super.noSuchMethod(Invocation.method(#newTempPath, [suffix]),
          returnValue: _i3.Future<String>.value(''),
          returnValueForMissingStub:
              _i3.Future<String>.value('')) as _i3.Future<String>);

  @override
  _i3.Future<void> addClip(_i5.VideoClip? clip) =>
      (super.noSuchMethod(Invocation.method(#addClip, [clip]),
          returnValue: _i3.Future<void>.value(),
          returnValueForMissingStub:
              _i3.Future<void>.value()) as _i3.Future<void>);

  @override
  _i3.Future<void> updateClip(_i5.VideoClip? clip) =>
      (super.noSuchMethod(Invocation.method(#updateClip, [clip]),
          returnValue: _i3.Future<void>.value(),
          returnValueForMissingStub:
              _i3.Future<void>.value()) as _i3.Future<void>);

  @override
  _i3.Future<void> deleteClip(_i5.VideoClip? clip) =>
      (super.noSuchMethod(Invocation.method(#deleteClip, [clip]),
          returnValue: _i3.Future<void>.value(),
          returnValueForMissingStub:
              _i3.Future<void>.value()) as _i3.Future<void>);

  @override
  _i3.Future<void> deleteTempFile(String? path) =>
      (super.noSuchMethod(Invocation.method(#deleteTempFile, [path]),
          returnValue: _i3.Future<void>.value(),
          returnValueForMissingStub:
              _i3.Future<void>.value()) as _i3.Future<void>);

  @override
  _i3.Future<List<_i5.VideoClip>> loadClips() =>
      (super.noSuchMethod(Invocation.method(#loadClips, []),
          returnValue:
              _i3.Future<List<_i5.VideoClip>>.value(<_i5.VideoClip>[]),
          returnValueForMissingStub:
              _i3.Future<List<_i5.VideoClip>>.value(<_i5.VideoClip>[])) as
          _i3.Future<List<_i5.VideoClip>>);

  @override
  _i3.Future<void> saveClips(List<_i5.VideoClip>? clips) =>
      (super.noSuchMethod(Invocation.method(#saveClips, [clips]),
          returnValue: _i3.Future<void>.value(),
          returnValueForMissingStub:
              _i3.Future<void>.value()) as _i3.Future<void>);

  @override
  _i3.Future<void> clearAll() =>
      (super.noSuchMethod(Invocation.method(#clearAll, []),
          returnValue: _i3.Future<void>.value(),
          returnValueForMissingStub:
              _i3.Future<void>.value()) as _i3.Future<void>);
}
